#! /usr/bin/python
import os
import sys;
import shutil;

def main():
    if(len(sys.argv) > 1):
        if(sys.argv[1] == 'pull'):
            pull()
        elif(sys.argv[1] == 'push'):
            push()
        else:
            print('Invalid argument!')
    else:
        print('Please pass some arguments: (pull or push)')


def pull():
    shutil.copyfile('/home/kwanele/Art/Projects/Configs/sway/config', '/home/kwanele/.config/sway/config')
    shutil.copyfile('/home/kwanele/Art/Projects/Configs/sway/config', '/home/kwanele/.config/sway/statusbar.sh')
    shutil.copyfile('/home/kwanele/Art/Projects/Configs/kitty/kitty.conf', '/home/kwanele/.config/kitty/kitty.conf')
    shutil.copyfile('/home/kwanele/Art/Projects/Configs/.zshrc', '/home/kwanele/.zshrc')
    shutil.copyfile('/home/kwanele/Art/Projects/Configs/.tmux.conf', '/home/kwanele/.tmux.conf')
    os.system('source ~/.zshrc')
    print('Done! configs pulled successfully!!!')

def push():
    shutil.copyfile('/home/kwanele/.config/sway/config','/home/kwanele/Art/Projects/Configs/sway/config')
    shutil.copyfile('/home/kwanele/.config/sway/statusbar.sh','/home/kwanele/Art/Projects/Configs/sway/statusbar.sh')
    shutil.copyfile( '/home/kwanele/.config/kitty/kitty.conf', '/home/kwanele/Art/Projects/Configs/kitty/kitty.conf')
    shutil.copyfile( '/home/kwanele/.zshrc','/home/kwanele/Art/Projects/Configs/.zshrc')
    shutil.copyfile( '/home/kwanele/.tmux.conf','/home/kwanele/Art/Projects/Configs/.tmux.conf')
    os.system('cd ~/Art/Projects/Configs && git add . && git commit -m "-update configs" && git push')
    print('Done! configs pushed successfully!!!')

main()
